source 'https://rubygems.org'
ruby '2.5.1'

gem 'pg'
gem 'activesupport'
gem 'activerecord', require: 'active_record'
gem 'oj'
gem 'dotenv'
gem 'pry'
gem 'rake'
gem 'progress_bar'
gem 'auto_strip_attributes'
gem 'pluck_to_hash'
gem 'active_record_migrations'
gem 'god'
gem 'faker'
