default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DB_URL'] %>
  pool: 5
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
